#spring:
#  datasource:
#    url: jdbc:mysql://106.14.46.10:3306/gulimall_sms?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto

#com.example.gulimall.common.validator.annotation.message="必须提交指定的值"