server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 106.14.46.10:8848

    alicloud:
      oss:
        endpoint: oss-cn-shanghai.aliyuncs.com
        bucket: hurried1y-gulimall

      access-key: LTAI5t69ZytD5J8w5AYimB7W
      secret-key: 2r9prUmNapAaPy1shhPFrs6pevH8x1

  application:
    name: gulimall-third-party
